package org.benf.cfr.tests;

import java.util.HashMap;
import java.util.Map;

/* HASH MAP SHOULD NOT NPE! */
public class HashMapNullKeyTest {

    private static class HashThis {
        private final int hascode;

        public HashThis(int hash) {
            this.hascode = hash;
        }

        @Override
        public int hashCode() {
            return hascode;
        }

        @Override
        public boolean equals(Object obj) {
            if (!(obj instanceof HashThis)) return false;
            HashThis other = (HashThis)obj;
            return other.hascode == hascode;
        }
    }

    public static void main(String ... args) {
        Map<HashThis, Integer> map = new HashMap<HashThis, Integer>();
if (true) {
    map.put(new HashThis(0), null);
    map.put(new HashThis(32), null);
}
    map.put(new HashThis(64), null);
    map.put(new HashThis(96), null);
    map.put(new HashThis(128), null);
    map.put(new HashThis(160), null);
    map.put(new HashThis(192), null);
    map.put(new HashThis(224), null);
    map.put(new HashThis(256), null);
    map.put(new HashThis(288), null);
    map.put(new HashThis(320), null);
    map.put(new HashThis(352), null);
map.put( new HashThis(384), null);
map.put( new HashThis(416), null);
map.put( new HashThis(448), null);
map.put( new HashThis(480), null);
map.put( new HashThis(512), null);
map.put( new HashThis(544), null);
map.put( new HashThis(576), null);
map.put( new HashThis(608), null);
map.put( new HashThis(640), null);
map.put( new HashThis(672), null);
map.put( new HashThis(704), null);
map.put( new HashThis(736), null);
map.put( new HashThis(768), null);
map.put( new HashThis(800), null);
map.put( new HashThis(832), null);
map.put( new HashThis(864), null);
map.put( new HashThis(896), null);
map.put( new HashThis(928), null);
map.put( new HashThis(960), null);
map.put( new HashThis(992), null);
map.put( new HashThis(1024), null);
map.put( new HashThis(1056), null);
map.put( new HashThis(1088), null);
map.put( new HashThis(1120), null);
map.put( new HashThis(1152), null);
map.put( new HashThis(1184), null);
map.put( new HashThis(1216), null);
map.put( new HashThis(1248), null);
map.put( new HashThis(1280), null);
map.put( new HashThis(1312), null);
map.put( new HashThis(1344), null);
map.put( new HashThis(1376), null);
map.put( new HashThis(1408), null);
map.put( new HashThis(1440), null);
map.put( new HashThis(1472), null);
map.put( new HashThis(1504), null);
map.put( new HashThis(1536), null);
map.put( new HashThis(1568), null);
map.put( new HashThis(1600), null);
map.put( new HashThis(1632), null);
map.put( new HashThis(1664), null);
map.put( new HashThis(1696), null);
map.put( new HashThis(1728), null);
map.put( new HashThis(1760), null);
map.put( new HashThis(1792), null);
map.put( new HashThis(1824), null);
map.put( new HashThis(1856), null);
map.put( new HashThis(1888), null);
map.put( new HashThis(1920), null);
map.put( new HashThis(1952), null);
map.put( new HashThis(1984), null);
map.put( new HashThis(2016), null);
map.put( new HashThis(2048), null);
map.put( new HashThis(2080), null);
map.put( new HashThis(2112), null);
map.put( new HashThis(2144), null);
map.put( new HashThis(2176), null);
map.put( new HashThis(2208), null);
map.put( new HashThis(2240), null);
map.put( new HashThis(2272), null);
map.put( new HashThis(2304), null);
map.put( new HashThis(2336), null);
map.put( new HashThis(2368), null);
map.put( new HashThis(2400), null);
map.put( new HashThis(2432), null);
map.put( new HashThis(2464), null);
map.put( new HashThis(2496), null);
map.put( new HashThis(2528), null);
map.put( new HashThis(2560), null);
map.put( new HashThis(2592), null);
map.put( new HashThis(2624), null);
map.put( new HashThis(2656), null);
map.put( new HashThis(2688), null);
map.put( new HashThis(2720), null);
map.put( new HashThis(2752), null);
map.put( new HashThis(2784), null);
map.put( new HashThis(2816), null);
map.put( new HashThis(2848), null);
map.put( new HashThis(2880), null);
map.put( new HashThis(2912), null);
map.put( new HashThis(2944), null);
map.put( new HashThis(2976), null);
map.put( new HashThis(3008), null);
map.put( new HashThis(3040), null);
map.put( new HashThis(3072), null);
map.put( new HashThis(3104), null);
map.put( new HashThis(3136), null);
map.put( new HashThis(3168), null);
map.put( new HashThis(3200), null);
map.put( new HashThis(3232), null);
map.put( new HashThis(3264), null);
map.put( new HashThis(3296), null);
map.put( new HashThis(3328), null);
map.put( new HashThis(3360), null);
map.put( new HashThis(3392), null);
map.put( new HashThis(3424), null);
map.put( new HashThis(3456), null);
map.put( new HashThis(3488), null);
map.put( new HashThis(3520), null);
map.put( new HashThis(3552), null);
map.put( new HashThis(3584), null);
map.put( new HashThis(3616), null);
map.put( new HashThis(3648), null);
map.put( new HashThis(3680), null);
map.put( new HashThis(3712), null);
map.put( new HashThis(3744), null);
map.put( new HashThis(3776), null);
map.put( new HashThis(3808), null);
map.put( new HashThis(3840), null);
map.put( new HashThis(3872), null);
map.put( new HashThis(3904), null);
map.put( new HashThis(3936), null);
map.put( new HashThis(3968), null);
map.put( new HashThis(4000), null);
map.put( new HashThis(4032), null);
map.put( new HashThis(4064), null);
map.put( new HashThis(4096), null);
map.put( new HashThis(4128), null);
map.put( new HashThis(4160), null);
map.put( new HashThis(4192), null);
map.put( new HashThis(4224), null);
map.put( new HashThis(4256), null);
map.put( new HashThis(4288), null);
map.put( new HashThis(4320), null);
map.put( new HashThis(4352), null);
map.put( new HashThis(4384), null);
map.put( new HashThis(4416), null);
map.put( new HashThis(4448), null);
map.put( new HashThis(4480), null);
map.put( new HashThis(4512), null);
map.put( new HashThis(4544), null);
map.put( new HashThis(4576), null);
map.put( new HashThis(4608), null);
map.put( new HashThis(4640), null);
map.put( new HashThis(4672), null);
map.put( new HashThis(4704), null);
map.put( new HashThis(4736), null);
map.put( new HashThis(4768), null);
map.put( new HashThis(4800), null);
map.put( new HashThis(4832), null);
map.put( new HashThis(4864), null);
map.put( new HashThis(4896), null);
map.put( new HashThis(4928), null);
map.put( new HashThis(4960), null);
map.put( new HashThis(4992), null);
map.put( new HashThis(5024), null);
map.put( new HashThis(5056), null);
map.put( new HashThis(5088), null);
map.put( new HashThis(5120), null);
map.put( new HashThis(5152), null);
map.put( new HashThis(5184), null);
map.put( new HashThis(5216), null);
map.put( new HashThis(5248), null);
map.put( new HashThis(5280), null);
map.put( new HashThis(5312), null);
map.put( new HashThis(5344), null);
map.put( new HashThis(5376), null);
map.put( new HashThis(5408), null);
map.put( new HashThis(5440), null);
map.put( new HashThis(5472), null);
map.put( new HashThis(5504), null);
map.put( new HashThis(5536), null);
map.put( new HashThis(5568), null);
map.put( new HashThis(5600), null);
map.put( new HashThis(5632), null);
map.put( new HashThis(5664), null);
map.put( new HashThis(5696), null);
map.put( new HashThis(5728), null);
map.put( new HashThis(5760), null);
map.put( new HashThis(5792), null);
map.put( new HashThis(5824), null);
map.put( new HashThis(5856), null);
map.put( new HashThis(5888), null);
map.put( new HashThis(5920), null);
map.put( new HashThis(5952), null);
map.put( new HashThis(5984), null);
map.put( new HashThis(6016), null);
map.put( new HashThis(6048), null);
map.put( new HashThis(6080), null);
map.put( new HashThis(6112), null);
map.put( new HashThis(6144), null);
map.put( new HashThis(6176), null);
map.put( new HashThis(6208), null);
map.put( new HashThis(6240), null);
map.put( new HashThis(6272), null);
map.put( new HashThis(6304), null);
map.put( new HashThis(6336), null);
map.put( new HashThis(6368), null);
map.put( new HashThis(6400), null);
map.put( new HashThis(6432), null);
map.put( new HashThis(6464), null);
map.put( new HashThis(6496), null);
map.put( new HashThis(6528), null);
map.put( new HashThis(6560), null);
map.put( new HashThis(6592), null);
map.put( new HashThis(6624), null);
map.put( new HashThis(6656), null);
map.put( new HashThis(6688), null);
map.put( new HashThis(6720), null);
map.put( new HashThis(6752), null);
map.put( new HashThis(6784), null);
map.put( new HashThis(6816), null);
map.put( new HashThis(6848), null);
map.put( new HashThis(6880), null);
map.put( new HashThis(6912), null);
map.put( new HashThis(6944), null);
map.put( new HashThis(6976), null);
map.put( new HashThis(7008), null);
map.put( new HashThis(7040), null);
map.put( new HashThis(7072), null);
map.put( new HashThis(7104), null);
map.put( new HashThis(7136), null);
map.put( new HashThis(7168), null);
map.put( new HashThis(7200), null);
map.put( new HashThis(7232), null);
map.put( new HashThis(7264), null);
map.put( new HashThis(7296), null);
map.put( new HashThis(7328), null);
map.put( new HashThis(7360), null);
map.put( new HashThis(7392), null);
map.put( new HashThis(7424), null);
map.put( new HashThis(7456), null);
map.put( new HashThis(7488), null);
map.put( new HashThis(7520), null);
map.put( new HashThis(7552), null);
map.put( new HashThis(7584), null);
map.put( new HashThis(7616), null);
map.put( new HashThis(7648), null);
map.put( new HashThis(7680), null);
map.put( new HashThis(7712), null);
map.put( new HashThis(7744), null);
map.put( new HashThis(7776), null);
map.put( new HashThis(7808), null);
map.put( new HashThis(7840), null);
map.put( new HashThis(7872), null);
map.put( new HashThis(7904), null);
map.put( new HashThis(7936), null);
map.put( new HashThis(7968), null);
map.put( new HashThis(8000), null);
map.put( new HashThis(8032), null);
map.put( new HashThis(8064), null);
map.put( new HashThis(8096), null);
map.put( null , null);

    }
}
